import { readFileSync, existsSync, readdirSync } from 'node:fs';
import assert from 'node:assert/strict';

const site = JSON.parse(readFileSync('content/generated/site.json', 'utf8'));
const home = JSON.parse(readFileSync('content/generated/home.json', 'utf8'));
const pages = [home, ...JSON.parse(readFileSync('content/generated/pages.json', 'utf8'))];
const origin = 'https://i-can-smell-you-from-here.github.io/';
const decode = text => text.replace(/&amp;/g, '&').replace(/&quot;/g, '"').replace(/&#x27;|&#39;/g, "'").replace(/&lt;/g, '<').replace(/&gt;/g, '>');
const visible = html => decode(html.replace(/<(script|style)\b[^>]*>[\s\S]*?<\/\1>/gi, '').replace(/<[^>]+>/g, ' ')).replace(/\s+/g, ' ').trim();
const titles = new Set(), descriptions = new Set();
const results = [];
assert.equal(pages.length, 6);
assert.equal(site.hosting.basePath, '');
assert.equal(site.readyForLaunch, true);
for (const page of pages) {
  const path = `out/${page.slug ? `${page.slug}/` : ''}index.html`;
  assert.ok(existsSync(path), `Missing ${path}`);
  const html = readFileSync(path, 'utf8');
  const title = decode(html.match(/<title>([^<]+)<\/title>/)?.[1] ?? '');
  const description = decode(html.match(/<meta name="description" content="([^"]+)"/)?.[1] ?? '');
  const canonical = decode(html.match(/<link rel="canonical" href="([^"]+)"/)?.[1] ?? '');
  const h1 = [...html.matchAll(/<h1\b[^>]*>([\s\S]*?)<\/h1>/g)];
  assert.equal(h1.length, 1, `${page.slug}: H1 count`);
  assert.equal(visible(h1[0][1]), page.hero.heading);
  assert.equal(title, page.title);
  assert.ok(title.length <= 60);
  assert.equal(description, page.description);
  assert.ok(description.length <= 160);
  assert.equal(canonical, `${origin}${page.slug ? `${page.slug}/` : ''}`);
  assert.ok(!titles.has(title), 'Duplicate title'); titles.add(title);
  assert.ok(!descriptions.has(description), 'Duplicate description'); descriptions.add(description);
  assert.ok(!/<meta name="(?:robots|googlebot)"[^>]*content="[^"]*noindex/i.test(html));
  const body = html.match(/<main\b[^>]*>([\s\S]*?)<\/main>/)?.[1] ?? '';
  const text = visible(body);
  assert.ok(text.length > 2500, `${page.slug}: body too thin`);
  assert.ok(!/Riftfall|Portal Dark v1|template preview|placeholder|Boss Drops|Latest Rewards|Working Codes|Map Routes|example\.github\.io|Yorich|Fact Pack|Evidence ID|Generated by|SEO audit|we could not verify/i.test(html));
  assert.ok(!/href="#(?:codes|guide)"/.test(html));
  assert.ok(!html.includes(`${origin}i-can-smell-you-from-here/`));
  assert.ok(!/href="\/i-can-smell-you-from-here\//.test(html));
  assert.equal((html.match(/<footer\b/g) ?? []).length, 1, 'Duplicate footer');
  const header = html.match(/<header\b[^>]*>([\s\S]*?)<\/header>/)?.[1] ?? '';
  const footer = html.match(/<footer\b[^>]*>([\s\S]*?)<\/footer>/)?.[1] ?? '';
  for (const slug of ['endings','where-to-play','idimya','controls','guide']) {
    assert.ok(header.includes(`href="/${slug}/"`), `Header missing ${slug}`);
    assert.ok(footer.includes(`href="/${slug}/"`), `Footer missing ${slug}`);
  }
  for (const slug of ['endings','where-to-play','idimya','controls']) {
    if (!page.slug) assert.ok(body.includes(`href="/${slug}/"`), `Home body missing ${slug}`);
  }
  const sectionCheck = section => {
    assert.ok(body.includes(`id="${section.id}"`), `Missing section ${section.id}`);
    const strings = [section.heading,section.eyebrow,section.intro,...(section.paragraphs ?? []),...(section.steps ?? []).flatMap(step => [step.heading,step.description]),...(section.links ?? []).flatMap(link => [link.label,link.description])].filter(Boolean);
    for (const str of strings) assert.ok(text.includes(str.replace(/\s+/g,' ')), `Dropped content: ${str.slice(0,80)}`);
    const tableCheck = table => {
      if (!table) return;
      for (const str of [table.caption,...table.columns,...table.rows.flat()]) assert.ok(text.includes(str), `Dropped table cell ${str}`);
    };
    tableCheck(section.table);
    for (const sub of section.subsections ?? []) { for (const str of [sub.heading,...sub.paragraphs,...(sub.bullets ?? [])]) assert.ok(text.includes(str)); tableCheck(sub.table); }
  };
  page.sections.forEach(sectionCheck);
  for (const item of page.faq ?? []) { assert.ok(text.includes(item.question)); assert.ok(text.includes(item.answer)); }
  const ids = [...html.matchAll(/\bid="([^"]+)"/g)].map(match => match[1]);
  assert.equal(ids.length,new Set(ids).size, 'Duplicate IDs');
  for (const match of html.matchAll(/href="([^"]+)"/g)) {
    const href = decode(match[1]);
    if (href.startsWith('#')) assert.ok(ids.includes(href.slice(1)), `Broken anchor ${href}`);
    else if (href.startsWith('/')) {
      const target = href.split('#')[0];
      assert.ok(existsSync(`out${target}${target.endsWith('/') ? 'index.html' : ''}`), `Broken link ${href}`);
    }
  }
  for (const match of html.matchAll(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/g)) {
    const data = JSON.parse(match[1]);
    assert.ok(!/"(?:genre|name)":""/.test(JSON.stringify(data)));
    if (data['@type'] === 'FAQPage') assert.equal(data.mainEntity.length, page.faq.length);
    if (data['@type'] === 'BreadcrumbList') assert.equal(data.itemListElement.at(-1).name,page.navLabel);
  }
  const words = text.match(/[A-Za-z0-9]+(?:['’-][A-Za-z0-9]+)*/g)?.length ?? 0;
  results.push({slug:page.slug || '/',title,titleCharacters:title.length,description,descriptionCharacters:description.length,h1:page.hero.heading,canonical,visibleWords:words});
}
const sitemap = readFileSync('out/sitemap.xml','utf8');
for (const result of results) assert.ok(sitemap.includes(`<loc>${result.canonical}</loc>`));
assert.equal((sitemap.match(/<loc>/g) ?? []).length,6);
const robots = readFileSync('out/robots.txt','utf8');
assert.ok(robots.includes('Allow: /') && !robots.includes('Disallow: /'));
assert.ok(robots.includes(`Sitemap: ${origin}sitemap.xml`));
assert.ok(existsSync('out/.nojekyll'));
assert.equal(JSON.parse(readFileSync('out/manifest.webmanifest','utf8')).icons[0].type,'image/webp');
assert.ok(!existsSync('out/CNAME') || Boolean(process.env.NEXT_PUBLIC_CUSTOM_DOMAIN?.trim()));
const integrations = JSON.parse(readFileSync('content/generated/integrations.json', 'utf8'));
const measurementId = (process.env.NEXT_PUBLIC_GA_MEASUREMENT_ID?.trim() || integrations.gaMeasurementId || '').toUpperCase();
if (/^G-[A-Z0-9]+$/.test(measurementId)) {
  const htmlFiles = directory => readdirSync(directory, { withFileTypes: true }).flatMap(entry => {
    const path = `${directory}/${entry.name}`;
    return entry.isDirectory() ? htmlFiles(path) : entry.name.endsWith('.html') ? [path] : [];
  });
  for (const path of htmlFiles('out')) {
    const html = readFileSync(path, 'utf8');
    // Ad iframe documents are noindex resources, not site pages. They must not
    // send additional page views; every actual page still gets the GA checks.
    if (/^out\/ads\/adsterra-(desktop|mobile|native)\.html$/.test(path)) {
      assert.ok(/<meta name="robots" content="noindex">/.test(html));
      assert.ok(!html.includes('www.googletagmanager.com/gtag/js'));
      continue;
    }
    const head = html.match(/<head\b[^>]*>([\s\S]*?)<\/head>/i)?.[1] ?? '';
    const scripts = [...html.matchAll(/<script\b([^>]*)>([\s\S]*?)<\/script>/gi)];
    const loaders = scripts.filter(script => script[1].includes('www.googletagmanager.com/gtag/js'));
    // React's hydration payload serializes the inline code as text, without executing it.
    const initializers = scripts.filter(script => !/^\s*self\.__next_f\./.test(script[2]) && /\bgtag\(['"]config['"]/.test(script[2]));
    assert.equal(loaders.length, 1, `${path}: must have exactly one Google tag loader`);
    assert.equal(initializers.length, 1, `${path}: must have exactly one GA initializer`);
    assert.ok(head.includes(loaders[0][0]) && head.includes(initializers[0][0]), `${path}: Google tag must be in the static head`);
    assert.ok(loaders[0][1].includes(`gtag/js?id=${measurementId}`));
    assert.ok(/\basync\b/.test(loaders[0][1]));
    assert.ok(initializers[0][2].includes(`gtag('config', ${JSON.stringify(measurementId)})`));
  }
  console.log('Google tag QA passed: one loader and initializer in the static head of every exported HTML page.');
}
console.log('SEO QA passed: all six pages, rich content, navigation, anchors, metadata, schema, sitemap and robots.');
console.log(JSON.stringify(results,null,2));
